//
//  KeyboardCommandSource.swift
//
//  Copyright © 2026 Doug Russell. All rights reserved.
//

import Carbon
import CoreGraphics
import os

/// Default key bindings: CGKeyCode → command fired when CapsLock is held as a modifier.
public let defaultKeyboardBindings: [CGKeyCode: ScreenReaderCommand] = [
    CGKeyCode(kVK_UpArrow):    .moveUp,
    CGKeyCode(kVK_DownArrow):  .moveDown,
    CGKeyCode(kVK_LeftArrow):  .moveLeft,
    CGKeyCode(kVK_RightArrow): .moveRight,
    CGKeyCode(kVK_ANSI_A):     .readAll,
]

/// A `CommandSource` driven by CapsLock (as a modifier key) combined with
/// keys observed via a CGEventTap.
///
/// Uses an active, head-inserted tap at the HID event level so that events
/// which trigger a command are consumed before reaching the focused app.
/// KeyUp events for consumed keys are also suppressed to avoid orphaned
/// key-up delivery.
///
/// Note: if the user has remapped CapsLock → Escape in System Settings the
/// tap still functions correctly (ScancodeObserver tracks the physical key at
/// the raw HID layer), but the Escape event generated by the physical CapsLock
/// press will reach the focused app since it is not a bound key code.
@MainActor
public final class KeyboardCommandSource: CommandSource {
    public nonisolated let identifier: String
    public nonisolated let dispatch: AsyncStream<ScreenReaderCommand>
    private let dispatchContinuation: AsyncStream<ScreenReaderCommand>.Continuation

    /// Maps CGKeyCode → command. Read at callback time, so reassigning remaps
    /// keys without recreating the tap.
    public var bindings: [CGKeyCode: ScreenReaderCommand]

    private let capsLock: CapsLock
    private var capsLockDown: Bool = false
    private var capsLockKeyStateTask: Task<Void, any Error>?
    private var tap: EventTap!
    private var runLoopSource: CFRunLoopSource!

    /// - Parameters:
    ///   - capsLock: `CapsLock` instance that tracks the modifier state.
    ///   - bindings: Initial keyCode→command map.
    public init(
        identifier: String = "keyboard",
        capsLock: CapsLock,
        bindings: [CGKeyCode: ScreenReaderCommand]
    ) throws {
        self.identifier = identifier
        self.capsLock = capsLock
        self.bindings = bindings
        (dispatch, dispatchContinuation) = AsyncStream<ScreenReaderCommand>.makeStream()
        let tap = try EventTap(
            configuration: .active,
            eventsOfInterest: EventTap.eventMask(eventTypes: [.keyDown, .keyUp])
        ) { [weak self] event in
            self?.handle(event: &event)
        }
        self.tap = tap
        runLoopSource = tap.runLoopSource(order: 0)
        CFRunLoopAddSource(
            CFRunLoopGetMain(),
            runLoopSource,
            .defaultMode
        )
        let capsLockKeyStateStream = capsLock.stream
        capsLockKeyStateTask = capsLockKeyStateStream
            .target(
                self,
                priority: .userInitiated,
                action: KeyboardCommandSource.yield(keyState:)
            )
    }

    isolated deinit {
        CFRunLoopRemoveSource(
            CFRunLoopGetMain(),
            runLoopSource,
            .defaultMode
        )
        capsLockKeyStateTask?.cancel()
    }

    private func yield(keyState: CapsLock.KeyState) {
        capsLockDown = keyState == .down
    }

    private func handle(event: inout EventTap.Event) {
        guard capsLockDown else {
            return
        }
        let eventType = event.eventType
        guard eventType == .keyDown || eventType == .keyUp else {
            return
        }
        let keyCode = event.keyCode
        guard let command = bindings[keyCode] else {
            return
        }
        // Any event we have a command for we should consume
        // both keyDown and keyUp
        event.cgEvent = nil
        guard eventType == .keyDown else {
            return
        }
        dispatchContinuation.yield(command)
    }
}
